-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 26, 2020 at 02:13 PM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.4.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `matrimony`
--

-- --------------------------------------------------------

--
-- Table structure for table `friend`
--

CREATE TABLE `friend` (
  `sender` varchar(5) NOT NULL,
  `receiver` varchar(5) NOT NULL,
  `status` varchar(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `friend`
--

INSERT INTO `friend` (`sender`, `receiver`, `status`) VALUES
('7', '2', '0'),
('1', '27', '0'),
('1', '40', '0'),
('12', '1', '1'),
('1', '18', '0');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `user_id` int(11) NOT NULL,
  `username` varchar(30) NOT NULL,
  `email` varchar(40) NOT NULL,
  `password` varchar(25) NOT NULL,
  `firstname` text NOT NULL,
  `lastname` text NOT NULL,
  `dob` date NOT NULL,
  `age` varchar(2) NOT NULL,
  `gender` varchar(10) NOT NULL,
  `nationality` varchar(20) NOT NULL,
  `religion` varchar(20) NOT NULL,
  `caste` varchar(30) NOT NULL,
  `phno` varchar(10) NOT NULL,
  `img` varchar(30) NOT NULL,
  `f_name` text NOT NULL,
  `m_name` text NOT NULL,
  `citizenship` text NOT NULL,
  `a_me` mediumtext NOT NULL,
  `b_group` varchar(10) NOT NULL,
  `m_status` varchar(20) NOT NULL,
  `l_known` varchar(50) NOT NULL,
  `m_ton` varchar(30) NOT NULL,
  `f_val` varchar(40) NOT NULL,
  `f_type` varchar(40) NOT NULL,
  `f_status` varchar(40) NOT NULL,
  `home` varchar(40) NOT NULL,
  `f_occ` varchar(50) NOT NULL,
  `m_occ` varchar(50) NOT NULL,
  `nob` tinyint(10) NOT NULL,
  `nob_m` tinyint(10) NOT NULL,
  `nos` tinyint(10) NOT NULL,
  `height` varchar(40) NOT NULL,
  `weight` varchar(40) NOT NULL,
  `p_status` varchar(40) NOT NULL,
  `b_type` varchar(20) NOT NULL,
  `complexion` varchar(30) NOT NULL,
  `e_habits` varchar(30) NOT NULL,
  `s_habit` varchar(20) NOT NULL,
  `d_habit` varchar(20) NOT NULL,
  `hobby` varchar(40) NOT NULL,
  `h_edu` varchar(30) NOT NULL,
  `employ` varchar(50) NOT NULL,
  `post` varchar(60) NOT NULL,
  `a_income` varchar(50) NOT NULL,
  `l_comp` text NOT NULL,
  `l_des` text NOT NULL,
  `address` mediumtext NOT NULL,
  `dist` text NOT NULL,
  `state` varchar(50) NOT NULL,
  `p_code` int(10) NOT NULL,
  `p_need` varchar(20) NOT NULL,
  `p_age` varchar(10) NOT NULL,
  `pm_status` varchar(40) NOT NULL,
  `p_religion` varchar(40) NOT NULL,
  `p_caste` varchar(30) NOT NULL,
  `pm_ton` varchar(40) NOT NULL,
  `p_post` varchar(60) NOT NULL,
  `status` varchar(2) NOT NULL,
  `time` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`user_id`, `username`, `email`, `password`, `firstname`, `lastname`, `dob`, `age`, `gender`, `nationality`, `religion`, `caste`, `phno`, `img`, `f_name`, `m_name`, `citizenship`, `a_me`, `b_group`, `m_status`, `l_known`, `m_ton`, `f_val`, `f_type`, `f_status`, `home`, `f_occ`, `m_occ`, `nob`, `nob_m`, `nos`, `height`, `weight`, `p_status`, `b_type`, `complexion`, `e_habits`, `s_habit`, `d_habit`, `hobby`, `h_edu`, `employ`, `post`, `a_income`, `l_comp`, `l_des`, `address`, `dist`, `state`, `p_code`, `p_need`, `p_age`, `pm_status`, `p_religion`, `p_caste`, `pm_ton`, `p_post`, `status`, `time`) VALUES
(1, 'Kevin', 'kevinjouse@gmail.com', 'kevinjouse', 'Kevin', 'J', '1995-02-17', '25', 'Male', 'Indian', 'Christian', 'Agamudayar', '6541239865', 'kevin.jpeg', 'John', 'Carolin', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Indian + English', 'Tamil', 'Liberal', 'Nuclear', 'Middle Class', 'own', 'Business', 'Housewife', 1, 0, 0, '5\'1 Feet', '66-70kg', 'Never Married', 'Average', 'Wheatish Brown', 'Non Vegetarian', 'No', 'sometime', 'Pets', 'Post Graduate', 'Government Job', 'Accounting, Banking & Finance', '4-5 lakh', 'State Bank Of India', 'Assistant Manager', '121, Nehru Street', 'Thanjavur', 'Tamil Nadu', 614602, 'Female', '22', 'Never Married', 'Christian', 'Agamudayar', 'Tamil', 'Accounting, Banking & Finance', 'F', '2020-10-10 18:35:56'),
(2, 'Denver', 'denver01@gmail.com', 'denver01', 'Madhav', 'E', '1992-01-21', '28', 'Male', 'Indian', 'Hindu', 'Baira', '6541897821', 'madhav.jpeg', 'Elango', 'Shanthi', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B+ve', 'Never Married', 'Indian + English', 'Malayalam', 'Modern', 'Nuclear', 'Upper Middle', 'own', 'Business', 'Housewife', 0, 0, 1, '5\'9 Feet', '66-70kg', 'Never Married', 'Athletic', 'Fair', 'Non Vegetarian', 'No', 'No', 'Acting', 'Post Graduate', 'Business In Partnership', 'Education & Training', '5-6 lakh', 'Brindhavan Higher Secondary School', 'Assistant Head Master', '21,Gandhi street', 'Thrissur', 'Kerala', 678905, 'Female', '24', 'Never Married', 'Hindu', 'Baira', 'Malayalam', 'Non Working', 'F', '2020-10-11 09:04:32'),
(3, 'Rio', 'rioshivan@gmail.com', 'rioshivan', 'Rio', 'S', '1993-01-13', '27', 'Male', 'Indian', 'Hindu', 'Banjara', '64231587', 'rio.jpeg', 'Shivan', 'Akila', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A1+ve', 'Never Married', 'Indian + English', 'Hindi', 'Orthodox', 'Joint', 'Rich', 'own', 'Government Job', 'Government Job', 1, 1, 1, '5\'8 Feet', '71-75kg', 'Never Married', 'Average', 'Wheatish', 'Egg Only', 'No', 'No', 'Acting', 'Graduate', 'Business Alone', 'Corporate Professionals', '9-10 lakh', 'Sai Private Ltd.', 'Manager', '51, Nethaji Street', 'Banka', 'Bihar', 812564, 'Female', '24', 'Never Married', 'Hindu', 'Banjara', 'Hindi', 'Science', 'P', '2020-10-11 13:42:09'),
(4, 'Hariharan', 'hariharan03@gmail.com', 'hariharan03', 'Hariharan', 'K', '1991-02-03', '29', 'Male', 'Indian', 'Hindu', 'Gounder ', '6321541265', 'hariharan.jpeg', 'Kamal', 'Poongudi', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Middle Class', 'rent', 'Retired', 'Housewife', 1, 0, 0, '5\'2 Feet', '71-75kg', 'Never Married', 'Average', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Photography', 'Graduate', 'Private Job', 'Engineering', '4-5 lakh', 'Kavin Car Private Ltd.', 'Executive Assistant', '431, Anna Nagar', 'Trichy', 'Tamil Nadu', 614621, 'Female', '25', 'Never Married', 'Hindu', 'Gounder ', 'Tamil', 'Engineering', 'F', '2020-10-11 13:53:31'),
(5, 'Raina', 'sureshraina@gmail.com', 'sureshraina', 'Raina', 'S', '1992-05-15', '28', 'Male', 'Indian', 'No Religious Belief', 'Nil', '6956325641', 'raina.jpeg', 'Suresh', 'Sarala', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O-ve', 'Never Married', 'Indian + English', 'Telugu', 'Orthodox', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 2, '5\'7 Feet', '61-65kg', 'Never Married', 'Slim', 'Wheatish', 'Vegetarian', 'sometime', 'sometime', 'Collections', 'Graduate', 'Private Job', 'Sales & Marketing', '0-1 lakh', 'Varan Private Ltd.', 'Brand Manager', '87, Mahatma Street', 'Hyderabad', 'Telangana', 501503, 'Female', '24', 'Never Married', 'No Religious Belief', 'Nil', 'Telugu', 'Education & Training', 'P', '2020-10-11 14:08:39'),
(6, 'Akash', 'maniakash23@gmail.com', 'maniakash23', 'Akash', 'M', '1995-03-23', '25', 'Male', 'Indian', 'Hindu', 'Halleer', '6231547896', 'akash.jpeg', 'Mani', 'Divya', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A-ve', 'Never Married', 'Only Indian', 'Gujarati', 'Liberal', 'Others', 'Middle Class', 'rent', 'Private Job', 'Housewife', 1, 1, 1, '5\'3 Feet', '56-60kg', 'Never Married', 'Slim', 'Fair', 'Non Vegetarian', 'Yes', 'sometime', 'Music', 'Graduate', 'Private Job', 'Sales & Marketing', '2-3 lakh', 'Sri Private Ltd.', 'Marketing Consultant', '76, Adams Street', 'Ahmedabad', 'Gujarat', 361139, 'Female', '22', 'Never Married', 'Hindu', 'Halleer', 'Gujarati', 'Sales & Marketing', 'F', '2020-10-12 04:37:55'),
(7, 'Sara', 'sarajames@gmail.com', 'sarajames', 'Sara', 'J', '1998-01-15', '22', 'Female', 'Indian', 'Hindu', 'Halleer', '6547891235', 'sara.jpeg', 'James', 'Shalini', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B+ve', 'Never Married', 'Only Indian', 'Gujarati', 'Liberal', 'Nuclear', 'Middle Class', 'rent', 'Retired', 'Housewife', 1, 1, 0, '5\'0 Feet', '56-60kg', 'Never Married', 'Slim', 'Wheatish', 'Non Vegetarian', 'No', 'No', 'Painting', 'Graduate', 'Private Job', 'Sales & Marketing', '2-3 lakh', 'Bala Private Ltd.', 'Copywriter', '09, Baker Street', 'Rajkot', 'Gujarat', 364439, 'Male', '25', 'Never Married', 'Hindu', 'Halleer', 'Gujarati', 'Sales & Marketing', 'F', '2020-10-12 04:53:34'),
(8, 'Harini', 'hariniramesh@gmail.com', 'hariniramesh', 'Harini', 'R', '1996-03-18', '24', 'Female', 'Indian', 'No Religious Belief', 'Nil', '7485961425', 'harini.jpeg', 'Ramesh', 'Hema', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A+ve', 'Never Married', 'Only Indian', 'Telugu', 'Liberal', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 1, '5\'1 Feet', '46-50kg', 'Never Married', 'Slim', 'Wheatish', 'Non Vegetarian', 'No', 'No', 'Puzzles/Crosswords', 'Graduate', 'Private Job', 'Education & Training', '2-3 lakh', 'Laurel Higher Secondary School', 'Teacher', '23, Bishop Wallers Avenue', 'Adilabad', 'Telangana', 521503, 'Male', '28', 'Never Married', 'No Religious Belief', 'Nil', 'Telugu', 'Sales & Marketing', 'P', '2020-10-12 05:08:45'),
(9, 'Jothi', 'jothimani@gmail.com', 'jothimani', 'Jothi', 'M', '1995-04-23', '25', 'Female', 'Indian', 'Hindu', 'Gounder', '6791378415', 'jothi.jpeg', 'Mani', 'Malini', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A1+ve', 'Never Married', 'Only Indian', 'Tamil', 'Modern', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 1, 1, 1, '5\'2 Feet', '51-55kg', 'Never Married', 'Slim', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Cooking', 'Graduate', 'Private Job', 'Engineering', '2-3 lakh', 'Laden Private Ltd.', 'Data Entry', '03, Ballard Street ', 'Chennai', 'Tamil Nadu', 601621, 'Male', '29', 'Never Married', 'Hindu', 'Gounder', 'Tamil', 'Engineering', 'F', '2020-10-12 05:19:04'),
(10, 'Megna', 'megnakrish@gmail.com', 'megnakrish', 'Megna', 'K', '1996-05-07', '24', 'Female', 'Indian', 'Hindu', 'Banjara', '9845123748', 'megna.jpeg', 'Krishnan', 'Malini', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B-ve', 'Never Married', 'Only Indian', 'Hindi', 'Liberal', 'Joint', 'Upper Middle', 'rent', 'Business', 'Housewife', 0, 0, 1, '5\'3 Feet', '51-55kg', 'Never Married', 'Slim', 'Wheatish', 'Egg Only', 'No', 'No', 'Arts/Handicrafts', 'Graduate', 'Private Job', 'Science', '2-3 lakh', 'Akil Institution', 'Mentor', '67, Barton Wright Road ', 'Bhojpur', 'Bihar', 813803, 'Male', '27', 'Never Married', 'Hindu', 'Banjara', 'Hindi', 'Corporate Professionals', 'P', '2020-10-12 05:46:27'),
(11, 'Jansi', 'jansikavin@gmail.com', 'jansikavin', 'Jansi', 'K', '1996-06-23', '24', 'Female', 'Indian', 'Hindu', 'Baira', '7621493781', 'jansi.jpeg', 'Kavin', 'Kamali', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A+ve', 'Never Married', 'Indian + English', 'Malayalam', 'Orthodox', 'Nuclear', 'Upper Middle', 'own', 'Government Job', 'Housewife', 1, 1, 0, '5\'1 Feet', '56-60kg', 'Never Married', 'Average', 'Fair', 'Non Vegetarian', 'No', 'No', 'Others', 'Diploma', 'Unemployed', 'Non Working', '0-1 lakh', 'Nil', 'Nil', '37, Clemens Road ', 'Kollam', 'Kerala', 678613, 'Male', '28', 'Never Married', 'Hindu', 'Baira', 'Malayalam', 'Education & Training', 'F', '2020-10-12 05:57:10'),
(12, 'Regina', 'reginajames@gmail.com', 'reginajames', 'Regina', 'J', '1998-01-31', '22', 'Female', 'Indian', 'Christian', 'Agamudayar', '7845123698', 'regina.jpeg', 'James', 'Dhanam', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 1, 1, 0, '5\'0 Feet', '51-55kg', 'Never Married', 'Slim', 'Fair', 'Non Vegetarian', 'No', 'No', 'Nature', 'Graduate', 'Government Job', 'Accounting, Banking & Finance', '2-3 lakh', 'Indian Bank', 'Clerk', '81, Coats Road', 'Chennai', 'Tamil Nadu', 601201, 'Male', '25', 'Never Married', 'Christian', 'Agamudayar', 'Tamil', 'Accounting, Banking & Finance', 'P', '2020-10-12 06:07:39'),
(13, 'Ram', 'ramkumar@gmail.com', 'ramkumar', 'Ram', 'K', '1994-06-14', '26', 'Male', 'Indian', 'Hindu', 'Alwar', '9563247916', 'ram.jpeg', 'Kumar', 'Kaviya', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B+ve', 'Never Married', 'Indian + English', 'Hindi', 'Modern', 'Joint', 'Rich', 'own', 'Business', 'Government Job', 1, 1, 0, '5\'6 Feet', '66-70kg', 'Never Married', 'Slim', 'Wheatish', 'Vegetarian', 'No', 'No', 'Gardening/Landscaping', 'Post Graduate', 'Freelancer', 'Artists, Animators & Web Designers', '5-6 lakh', 'Infosys', 'Web Designer', '34, Davidson Street', 'Madurai', 'Tamil Nadu', 625018, 'Female', '23', 'Never Married', 'Hindu', 'Alwar', 'Tamil', 'Artists, Animators & Web Designers', 'P', '2020-10-12 06:37:51'),
(14, 'Srija', 'srijasaran@gmail.com', 'srijasaran', 'Srija', 'S', '1997-07-05', '23', 'Female', 'Indian', 'Hindu', 'Alwar', '8327465215', 'srija.jpeg', 'Saran', 'Srinithi', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A+ve', 'Never Married', 'Only Indian', 'Tamil', 'Traditional', 'Joint', 'Upper Middle', 'own', 'Business', 'Housewife', 1, 1, 0, '5\'2 Feet', '66-70kg', 'Never Married', 'Average', 'Wheatish Brown', 'Vegetarian', 'No', 'No', 'Dancing', 'Graduate', 'Private Job', 'Artists, Animators & Web Designers', '3-4 lakh', 'CTS', 'Web Designer', '671, Edward Park Road', 'Thanjavur', 'Tamil Nadu', 614601, 'Male', '26', 'Never Married', 'Hindu', 'Alwar', 'Tamil', 'Artists, Animators & Web Designers', 'P', '2020-10-12 08:54:37'),
(15, 'Saran', 'saransakthi@gmail.com', 'saransakthi', 'Saran', 'S', '1993-04-28', '27', 'Male', 'Indian', 'Hindu', 'Holar', '6737199154', 'saran.jpeg', 'Sakthi', 'Saranya', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A1+ve', 'Never Married', 'Only Indian', 'Kannada', 'Liberal', 'Joint', 'Upper Middle', 'own', 'Business', 'Housewife', 0, 0, 1, '5\'9 Feet', '71-75kg', 'Never Married', 'Average', 'Wheatish', 'Non Vegetarian', 'No', 'sometime', 'Collections', 'Post Graduate', 'Private Job', 'Medical & Healthcare', '5-6 lakh', 'Sri Hari Hospital', 'Medical Laboratory Tech', '41, Flowells Street', 'Kolar', 'Karnataka', 561259, 'Female', '23', 'Never Married', 'Hindu', 'Holar', 'Kannada', 'Hotel & Hospitality', 'P', '2020-10-12 09:15:48'),
(16, 'Harija', 'harijahari@gmail.com', 'harijahari', 'Harija', 'H', '1997-04-19', '23', 'Female', 'Indian', 'Hindu', 'Holar', '6289988748', 'harija.jpeg', 'Hariharan', 'Janani', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Kannada', 'Traditional', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 1, '5\'3 Feet', '61-65kg', 'Never Married', 'Slim', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Music', 'Graduate', 'Private Job', 'Hotel & Hospitality', '2-3 lakh', 'Kannan Hotel', 'Event Planner', '60, Francis Joseph Street', 'Bangalore Urban', 'Karnataka', 560959, 'Male', '27', 'Never Married', 'Hindu', 'Holar', 'Kannada', 'Medical & Healthcare', 'F', '2020-10-12 09:24:03'),
(17, 'Vignesh', 'vigneshvicky@gmail.com', 'vigneshvicky', 'Vignesh', 'K', '1989-05-12', '31', 'Male', 'Indian', 'Christian', 'Bantar', '9632147852', 'vignesh.jpeg', 'Kishore', 'Parvathi', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B+ve', 'Never Married', 'Only Indian', 'Bengali', 'Liberal', 'Nuclear', 'Upper Middle', 'own', 'Retired', 'Housewife', 1, 0, 0, '5\'8 Feet', '76-80kg', 'Never Married', 'Heavy', 'Fair', 'Non Vegetarian', 'No', 'sometime', 'Film Making', 'M.Phil', 'Private Job', 'Education & Training', '5-6 lakh', 'Palm Higher Secondary School', 'Head Master', '44, General Collins Road', 'Kolkata', 'West Bengal', 701274, 'Female', '26', 'Never Married', 'Christian', 'Bantar', 'Bengali', 'Science', 'F', '2020-10-12 09:38:28'),
(18, 'Vaishali', 'vaishali08@gmail.com', 'vaishali08', 'Vaishali', 'K', '1994-08-08', '26', 'Female', 'Indian', 'Christian', 'Bantar', '8855214697', 'vaishali.jpeg', 'Kennedy', 'Harsha', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B+ve', 'Never Married', 'Only Indian', 'Bengali', 'Orthodox', 'Joint', 'Rich', 'own', 'Government Job', 'Government Job', 1, 1, 0, '5\'4 Feet', '61-65kg', 'Never Married', 'Slim', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Arts/Handicrafts', 'Post Graduate', 'Private Job', 'Science', '3-4 lakh', 'Sairam Science Institution', 'Online ESL Instructor', '03, Gills Street', 'Darjeeling', 'West Bengal', 703274, 'Male', '31', 'Never Married', 'Hindu', 'Bantar', 'Bengali', 'Education & Training', 'P', '2020-10-12 09:50:09'),
(19, 'Vimal', 'vimal16@gmail.com', 'vimal16', 'Vimal', 'K', '1991-10-16', '29', 'Male', 'Indian', 'Hindu', 'Gounder', '7414785214', 'vimal.jpeg', 'Kailash', 'Menaha', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Tamil', 'Traditional', 'Joint', 'Lower Middle Class', 'rent', 'Retired', 'Housewife', 0, 0, 1, '5\'7 Feet', '66-70kg', 'Never Married', 'Average', 'Dark', 'Egg Only', 'No', 'No', 'Painting', 'Post Graduate', 'Private Job', 'Engineering', '3-4 lakh', 'Srisai Private Ltd.', 'Assistant Engineer', '33, Gregory Street ', 'Pudhukottai', 'Tamil Nadu', 615632, 'Female', '25', 'Never Married', 'Hindu', 'Gounder', 'Tamil', 'Engineering', 'F', '2020-10-12 10:01:50'),
(20, 'Pallavi', 'pallavi77@gmail.com', 'pallavi77', 'Pallavi', 'S', '1995-02-07', '25', 'Female', 'Indian', 'Hindu', 'Gounder', '8877547854', 'pallavi.jpeg', 'Selvam', 'Sarala', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A1+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Lower Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 1, '5\'2 Feet', '61-65kg', 'Never Married', 'Average', 'Wheatish Brown', 'Egg Only', 'No', 'No', 'Acting', 'Graduate', 'Private Job', 'Engineering', '2-3 lakh', 'Ladak Private Ltd.', 'Quality Engineer', '11, Hopman Street', 'Trichy', 'Tamil Nadu', 615621, 'Male', '29', 'Never Married', 'Hindu', 'Gounder', 'Tamil', 'Engineering', 'F', '2020-10-12 10:11:16'),
(21, 'Irfan', 'irfanmohamed@gmail.com', 'irfan07', 'Irfan', 'A', '1993-06-11', '27', 'Male', 'Indian', 'Muslim', 'Sheik', '6544561232', 'irfan.jpeg', 'Ahamed', 'Begam', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A+ve', 'Never Married', 'Only Indian', 'Tamil', 'Traditional', 'Joint', 'Upper Middle', 'own', 'Private Job', 'Housewife', 1, 1, 0, '5\'8 Feet', '71-75kg', 'Never Married', 'Average', 'Fair', 'Non Vegetarian', 'No', 'sometime', 'Nature', 'Graduate', 'Government Job', 'Accounting, Banking & Finance', '6-7 lakh', 'Union Bank Of India', 'Assistant Manager', '45, Jesson Street', 'Nagapattinam', 'Tamil Nadu', 612618, 'Female', '23', 'Never Married', 'Muslim', 'Sheik', 'Tamil', 'Non Working', 'P', '2020-10-12 10:31:53'),
(22, 'Noora', 'noora27@gmail.com', 'noora', 'Noora', 'M', '1997-08-27', '23', 'Female', 'Indian', 'Muslim', 'Sheik', '9512357895', 'noora.jpeg', 'Mohamed Ali', 'Roja', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B+ve', 'Never Married', 'Only Indian', 'Tamil', 'Traditional', 'Nuclear', 'Upper Middle', 'own', 'Government Job', 'Housewife', 1, 1, 0, '5\'4 Feet', '61-65kg', 'Never Married', 'Slim', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Music', 'Graduate', 'Unemployed', 'Non Working', '0-1 lakh', 'Nil', 'Nil', '99, Langs Garden Road', 'Coimbatore', 'Tamil Nadu', 617631, 'Male', '27', 'Never Married', 'Muslim', 'Sheik', 'Tamil', 'Accounting, Banking & Finance', 'F', '2020-10-15 06:12:58'),
(23, 'Kamila', 'kamilaibrahim@gmail.com', 'kamilaibrahim', 'Kamila', 'I', '1997-07-12', '23', 'Female', 'Indian', 'Muslim', 'Sheik', '8855269745', 'kamila.jpeg', 'Ibrahim', 'Noora', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A1+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 1, '5\'3 Feet', '66-70kg', 'Never Married', 'Slim', 'very Fair', 'Non Vegetarian', 'No', 'No', 'Cooking', 'Diploma', 'Unemployed', 'Non Working', '0-1 lakh', 'Nil', 'Nil', '36, Madley Street', 'Thirunelveli', 'Tamil Nadu', 623613, 'Male', '27', 'Never Married', 'Muslim', 'Sheik', 'Tamil', 'Accounting, Banking & Finance', 'P', '2020-10-15 06:33:10'),
(24, 'Mahesh', 'maheshraja@gmail.com', 'maheshraja', 'Mahesh', 'R', '1993-05-19', '27', 'Male', 'Indian', 'Hindu', 'Chettiar', '7447855848', 'mahesh.jpeg', 'Raja', 'Latha', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A+ve', 'Never Married', 'Only Indian', 'Malayalam', 'Traditional', 'Joint', 'Upper Middle', 'own', 'Government Job', 'Retired', 1, 1, 1, '5\'9 Feet', '66-70kg', 'Never Married', 'Slim', 'Fair', 'Vegetarian', 'No', 'No', 'Collections', 'Graduate', 'Government Job', 'Accounting, Banking & Finance', '5-6 lakh', 'Indian Overseas Bank', 'Assistant Manager', '33, Menads Street', 'Trichy', 'Tamil Nadu', 615602, 'Female', '24', 'Never Married', 'Hindu', 'Chettiar', 'Tamil', 'Accounting, Banking & Finance', 'P', '2020-10-15 09:35:21'),
(25, 'Krishnan', 'krishmanoj@gmail.com', 'krishmanoj', 'Krishnan', 'M', '1993-07-02', '27', 'Male', 'Indian', 'Hindu', 'Chettiar', '6565452145', 'krishnan.jpeg', 'Manoj', 'Rani', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O-ve', 'Never Married', 'Only Indian', 'Malayalam', 'Orthodox', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 1, '5\'7 Feet', '61-65kg', 'Never Married', 'Slim', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Photography', 'Graduate', 'Government Job', 'Accounting, Banking & Finance', '2-3 lakh', 'State Bank Of India', 'Clerk', '221, Murrays Gate Road', 'Alappuzha', 'Kerala', 671691, 'Female', '24', 'Never Married', 'Hindu', 'Chettiar', 'Malayalam', 'Accounting, Banking & Finance', 'F', '2020-10-15 09:42:57'),
(26, 'Mahat', 'mahatkishore@gmail.com', 'mahatkishore', 'Mahat', 'K', '1993-09-09', '27', 'Male', 'Indian', 'Hindu', 'Chettiar', '8745874569', 'mahat.jpeg', 'Kishore', 'Vaishnavi', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B+ve', 'Never Married', 'Only Indian', 'Kannada', 'Liberal', 'Nuclear', 'Rich', 'own', 'Government Job', 'Retired', 1, 1, 0, '6\'0 Feet', '61-65kg', 'Never Married', 'Athletic', 'Fair', 'Egg Only', 'No', 'No', 'Acting', 'Post Graduate', 'Government Job', 'Accounting, Banking & Finance', '9-10 lakh', 'Indian Bank', 'Manager', '55, Noble Street', 'Mysore', 'Karnataka', 560591, 'Female', '24', 'Never Married', 'Hindu', 'Chettiar', 'Kannada', 'Accounting, Banking & Finance', 'P', '2020-10-15 09:52:00'),
(27, 'Pooja', 'poojaram@gmail.com', 'pooojaram', 'Pooja', 'Ram', '1996-08-17', '24', 'Female', 'Indian', 'Hindu', 'Chettiar', '6548954895', 'pooja.jpeg', 'Ram', 'Maheshwari', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A1+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 1, '5\'1 Feet', '61-65kg', 'Never Married', 'Slim', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Puzzles/Crosswords', 'Graduate', 'Government Job', 'Accounting, Banking & Finance', '2-3 lakh', 'Repco Bank', 'Clerk', '341, Rex Street', 'Thanjavur', 'Tamil Nadu', 614605, 'Male', '27', 'Never Married', 'Hindu', 'Chettiar', 'Tamil', 'Accounting, Banking & Finance', 'F', '2020-10-15 10:00:40'),
(28, 'Swetha', 'swethajega@gmail.com', 'swethajega', 'Swetha', 'J', '1996-02-14', '24', 'Female', 'Indian', 'Hindu', 'Chettiar', '9636985125', 'swetha.jpeg', 'Jegadheesan', 'Rohini', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Malayalam', 'Liberal', 'Nuclear', 'Upper Middle', 'own', 'Government Job', 'Housewife', 1, 1, 0, '5\'3 Feet', '56-60kg', 'Never Married', 'Athletic', 'Wheatish', 'Vegetarian', 'No', 'No', 'Pets', 'Graduate', 'Government Job', 'Accounting, Banking & Finance', '4-5 lakh', 'Union Bank Of India', 'Assistant Manager', '49, Ritchie Street', 'Ernakulam', 'Kerala', 678690, 'Male', '27', 'Never Married', 'Hindu', 'Chettiar', 'Malayalam', 'Accounting, Banking & Finance', 'F', '2020-10-15 10:06:49'),
(29, 'Harshini', 'harshinikarthick@gmail.com', 'harshinikarthick', 'Harshini', 'K', '1996-03-07', '24', 'Female', 'Indian', 'Hindu', 'Chettiar', '6996632215', 'harshini.jpeg', 'Karthick', 'Karthiga', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Kannada', 'Modern', 'Nuclear', 'Rich', 'own', 'Government Job', 'Housewife', 1, 1, 0, '5\'2 Feet', '56-60kg', 'Never Married', 'Slim', 'Wheatish', 'Egg Only', 'No', 'No', 'Acting', 'Graduate', 'Government Job', 'Accounting, Banking & Finance', '5-6 lakh', 'Indian Bank', 'Assistant Manager', '77, Solomon Street', 'Kolar', 'Karnataka', 561591, 'Male', '27', 'Never Married', 'Hindu', 'Chettiar', 'Kannada', 'Accounting, Banking & Finance', 'P', '2020-10-15 10:15:05'),
(30, 'Asif', 'asifnainar@gmail.com', 'asifnainar', 'Asif', 'N', '1993-03-31', '27', 'Male', 'Indian', 'Muslim', 'Sheik', '7845845784', 'asif.jpeg', 'Nainar', 'Kamila', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A1+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Upper Middle', 'own', 'Private Job', 'Private Job', 0, 0, 1, '5\'6 Feet', '71-75kg', 'Never Married', 'Average', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Fishing', 'Post Graduate', 'Government Job', 'Accounting, Banking & Finance', '8-9 lakh', 'Indian Bank', 'Manager', '556, Stephenson Road & Lane', 'Madurai', 'Tamil Nadu', 625018, 'Female', '23', 'Never Married', 'Muslim', 'Sheik', 'Tamil', 'Non Working', 'P', '2020-10-15 10:31:30'),
(31, 'Rakesh', 'rakeshkannan@gmail.com', 'rakeshkannan', 'Rakesh', 'Kannan', '1992-03-28', '28', 'Male', 'Indian', 'Hindu', 'Kallar', '8525894379', 'rakesh.jpeg', 'Kannan', 'Kamala', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 1, '5\'7 Feet', '71-75kg', 'Never Married', 'Average', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Astrology', 'Graduate', 'Private Job', 'Engineering', '3-4 lakh', 'Vahan Private Ltd.', 'Maintenance Engineer', '33, Sullivan Street', 'Kancheepuram', 'Tamil Nadu', 612623, 'Female', '25', 'Never Married', 'Hindu', 'Kallar', 'Tamil', 'Engineering', 'F', '2020-10-15 17:46:30'),
(32, 'Sanjeev', 'sanjeev08@gmail.com', 'sanjeev08', 'Sanjeev', 'M', '1992-05-08', '28', 'Male', 'Indian', 'Hindu', 'Kallar', '7598463512', 'sanjeev.jpeg', 'Mathavan', 'Seetha', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A1+ve', 'Never Married', 'Only Indian', 'Tamil', 'Traditional', 'Joint', 'Upper Middle', 'own', 'Government Job', 'Housewife', 1, 1, 1, '6\'0 Feet', '66-70kg', 'Never Married', 'Average', 'Wheatish Brown', 'Vegetarian', 'No', 'No', 'Puzzles/Crosswords', 'Post Graduate', 'Private Job', 'Engineering', '7-8 lakh', 'Amazon', 'Technical Specialist', '77, Thomas Street', 'Erode', 'Tamil Nadu', 601621, 'Female', '25', 'Never Married', 'Hindu', 'Kallar', 'Tamil', 'Engineering', 'P', '2020-10-15 17:54:13'),
(33, 'Vishnu', 'vishnugopal@gmail.com', 'vishnugopal', 'Vishnu', 'G', '1992-06-13', '28', 'Male', 'Indian', 'Hindu', 'Kallar', '9595686848', 'vishnu.jpeg', 'Gopal', 'Shanthi', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Tamil', 'Modern', 'Nuclear', 'Lower Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 1, '5\'7 Feet', '66-70kg', 'Never Married', 'Average', 'Wheatish Brown', 'Non Vegetarian', 'No', 'sometime', 'Collections', 'Graduate', 'Private Job', 'Engineering', '3-4 lakh', 'Drago Private Ltd.', 'Data Entry', '74, Todhunter Nagar', 'Salem', 'Tamil Nadu', 612612, 'Female', '25', 'Never Married', 'Hindu', 'Kallar', 'Tamil', 'Engineering', 'F', '2020-10-15 18:03:10'),
(34, 'Madan', 'madankamal@gmail.com', 'madankamal', 'Madan', 'K', '1992-09-02', '28', 'Male', 'Indian', 'Hindu', 'Kallar', '8523697412', 'madan.jpeg', 'Kamal', 'Meena', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Tamil', 'Modern', 'Nuclear', 'Rich', 'own', 'Retired', 'Retired', 1, 1, 1, '5\'8 Feet', '66-70kg', 'Never Married', 'Slim', 'Wheatish Brown', 'Non Vegetarian', 'No', 'sometime', 'Gardening/Landscaping', 'Post Graduate', 'Business Alone', 'Engineering', '8-9 lakh', 'Madan Private Ltd.', 'Chief Engineer', '37, Umpherson Street ', 'Theni', 'Tamil Nadu', 604615, 'Female', '25', 'Never Married', 'Hindu', 'Kallar', 'Tamil', 'Engineering', 'P', '2020-10-15 18:10:28'),
(35, 'Meena', 'meenavasanth@gmail.com', 'meenavasanth', 'Meena', 'V', '1995-05-17', '25', 'Female', 'Indian', 'Hindu', 'Kallar', '8495625342', 'meena.jpeg', 'Vasanth', 'Saantha', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B+ve', 'Never Married', 'Only Indian', 'Tamil', 'Traditional', 'Nuclear', 'Upper Middle', 'own', 'Government Job', 'Housewife', 1, 1, 0, '5\'3 Feet', '61-65kg', 'Never Married', 'Slim', 'Wheatish', 'Non Vegetarian', 'No', 'No', 'Music', 'Graduate', 'Private Job', 'Engineering', '5-6 lakh', 'Infosys', 'Web Designer', '34, Williams Street', 'Nilgiris', 'Tamil Nadu', 624612, 'Male', '28', 'Never Married', 'Hindu', 'Kallar', 'Tamil', 'Engineering', 'P', '2020-10-15 18:18:23'),
(36, 'Nikitha', 'nikitharaja@gmail.com', 'nikitharaja', 'Nikitha', 'R', '1995-06-18', '25', 'Female', 'Indian', 'Hindu', 'Kallar', '8469758685', 'nikitha.jpeg', 'Raja', 'Meena', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Rich', 'own', 'Government Job', 'Housewife', 1, 1, 0, '5\'3 Feet', '56-60kg', 'Never Married', 'Slim', 'Wheatish', 'Vegetarian', 'No', 'No', 'Pets', 'Graduate', 'Private Job', 'Engineering', '8-9 lakh', 'Zoho', 'Software Engineer', '345, Cox Street', 'Thiruvallur', 'Tamil Nadu', 612630, 'Male', '28', 'Never Married', 'Hindu', 'Kallar', 'Tamil', 'Engineering', 'P', '2020-10-15 18:25:29'),
(37, 'Roshini', 'roshinihari@gmail.com', 'roshinihari', 'Roshini', 'H', '1995-05-31', '25', 'Female', 'Indian', 'Hindu', 'Kallar', '8798789878', 'roshini.jpeg', 'Hari', 'Gokila', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Middle Class', 'rent', 'Private Job', 'Housewife', 0, 0, 1, '5\'3 Feet', '56-60kg', 'Never Married', 'Slim', 'Wheatish Brown', 'Vegetarian', 'No', 'No', 'Collections', 'Graduate', 'Private Job', 'Engineering', '3-4 lakh', 'Varam Private Ltd.', 'Data Entry', '253, Branson Garden Street ', 'Thoothukudi', 'Tamil Nadu', 612607, 'Male', '28', 'Never Married', 'Hindu', 'Kallar', 'Tamil', 'Engineering', 'F', '2020-10-15 18:32:33'),
(38, 'Vanaja', 'vanajarani@gmail.com', 'vanajarani', 'Vanaja', 'M', '1995-10-11', '25', 'Female', 'Indian', 'Hindu', 'Kallar', '9988774857', 'vanaja.jpeg', 'Mohan', 'Rani', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'B+ve', 'Never Married', 'Only Indian', 'Tamil', 'Liberal', 'Nuclear', 'Middle Class', 'own', 'Private Job', 'Housewife', 0, 0, 1, '5\'4 Feet', '61-65kg', 'Never Married', 'Slim', 'Dark', 'Non Vegetarian', 'No', 'No', 'Arts/Handicrafts', 'Graduate', 'Private Job', 'Engineering', '3-4 lakh', 'Hyna Private Ltd.', 'Assistant Engineer', '374, Bamford Road', 'Vellore', 'Tamil Nadu', 632601, 'Male', '25', 'Never Married', 'Hindu', 'Kallar', 'Tamil', 'Engineering', 'F', '2020-10-15 18:41:13'),
(39, 'Anderson', 'anderson18@gmail.com', 'anderson18', 'Anderson', 'J', '1994-05-23', '26', 'Male', 'Indian', 'Christian', 'Chandala', '7595848685', 'anderson.jpeg', 'John', 'Ananthi', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'O+ve', 'Never Married', 'Only Indian', 'Malayalam', 'Liberal', 'Nuclear', 'Upper Middle', 'own', 'Government Job', 'Housewife', 1, 1, 0, '5\'10 Feet', '66-70kg', 'Never Married', 'Average', 'Wheatish Brown', 'Non Vegetarian', 'No', 'No', 'Nature', 'Graduate', 'Private Job', 'IT & Software Engineering', '5-6 lakh', 'Bogan Private Ltd.', 'Computer Programmer', '567, Baker Street', 'Palakkad', 'Kerala', 678690, 'Female', '24', 'Never Married', 'Christian', 'Chandala', 'Malayalam', 'IT & Software Engineering', 'P', '2020-10-15 18:54:14'),
(40, 'Katrina', 'katrinathomas@gmail.com', 'katrinathomas', 'Katrina', 'T', '1996-06-14', '24', 'Female', 'Indian', 'Christian', 'Chandala', '7753562526', 'katrina.jpeg', 'Thomas', 'Regina', 'Indian', 'I am courageous person and I will definitely travel throughout the entire life with you and I have great reputation in the society. I have great job in my hand and I will lead a beautiful life with you.', 'A+ve', 'Never Married', 'Only Indian', 'Malayalam', 'Traditional', 'Nuclear', 'Upper Middle', 'own', 'Government Job', 'Housewife', 1, 1, 0, '5\'3 Feet', '56-60kg', 'Never Married', 'Slim', 'Fair', 'Vegetarian', 'No', 'No', 'Cooking', 'Graduate', 'Private Job', 'IT & Software Engineering', '5-6 lakh', 'Infosys', 'Cloud Architect', '590, Arundale Street', 'Alappuzha', 'Kerala', 674612, 'Male', '26', 'Never Married', 'Christian', 'Chandala', 'Malayalam', 'IT & Software Engineering', 'P', '2020-10-15 19:01:47'),
(41, 'admin', 'matrimonybka@gmail.com', 'Admin@123', '', '', '0000-00-00', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '2020-10-16 04:13:39');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`user_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;